### ISSUE TITLE
tsoha vertaisarvio 1

### ISSUE THREAD

**Issue by aleksiskela** [ah-pasila/tsoha-running-routes#1]
Vertaisarvio totetutettu ilman testausmahdollisuutta. Arvio perustuu koodin tarkasteluun githubissa.

- routes-taulun aikaleiman sarakkeen nimi voisi olla creation_time tai muu täsmällisempi nimi
- numeric hyvä valinta length-sarakkeen tyyppiksi
- tietokannan rakenne järkevä
- taulujen lukumäärä tässä vaiheessa vielä alle vaaditun määrän
- lisäämällä layout.html voisi muita templateja lyhentää
- routes.py vielä alkuvaiheessa, mutta koodi on siistiä ja hyvin jäsenneltyä
- readme.md voisi olla README.md
- projektin aihe on hyvä ja mielenkiintoinen

**Comment by ah-pasila** [comment]
Kiitos palautteesta ja ehdotuksta! 
Pitkällisen asentelun jälkeen sain tänään sovelluksen tuotantoon: 
https://tsoha-running-routes.fly.dev/ - tämä ei ehdi arviointiin mukaan, mutta parin illan väännön jälkeen oli aika ilahduttavaa saada tuo Fly.io vihdoin toimimaan.
